print("HELLO WORLD!")
print("Di pa ako antok!")
print("Di mahal ni mc si selwyn")
print("Gaeeee")
print("Tangina ni ivan")
print("Hello Mofos")
print("Archie maitim")
are = input("TANGINA MO: ")
print("gusto ko ng kape.")